import NextAuth from "next-auth";

import GoogleProvider from 'next-auth/providers/google'

const handler= NextAuth({
    providers:[
        GoogleProvider({
            clientId:process.env.GOOGLE_CLIENT_ID,
            clientSecret:process.env.GOOGLE_CLIENT_SECRET
        })
    ]
})
export {handler as GET,handler as POST}



------------

 

'use client'

const { SessionProvider } = require("next-auth/react")

const AuthProvider =({children}) => {

    return (
        <SessionProvider>
            {children}
        </SessionProvider>
    )
}
export default AuthProvider


-------


 "use client";
import { signIn, signOut, useSession } from "next-auth/react";
import React from "react";

const Login = () => {
  const session = useSession();
  console.log(session);
  if (session.status === "loading") {
    return <p>Loading.....!</p>;
  }
  if (session.status === "authenticated") {
    return <button onClick={() => signOut("google")}>Logout from Google</button>
  }
  return (
    <div>
      <button onClick={() => signIn("google")}>Login with Google</button>
    </div>
  );
};
export default Login;
--------



Main LAyout

 import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./components/AuthProvider/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        {children}
        </AuthProvider>
      
        </body>
    </html>
  );
}
